baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Invalid Input"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-106752330-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "../xvrdm.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/xvrdm"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/xvrdm"
    weight = 5

[params]
    description = "A datascience journal."
    twitterAuthor = "@xvrdm"
    twitterSite = "@invalid_input"
    socialImgDir = "https://xvrdm.github.io/img/"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "clojure", "hy", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

